server:
  port: 14000

spring:
  main:
    allow-bean-definition-overriding: true  #允许Bean定义信息重写

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

app:
  pay:
    alipay:
      app-id: 2021000122601908
      merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqhGaVe6Kh8CJvAOYX5GGVHRz9yfNkNXaYqU0W2EXUCG8hzlCq+sF9uZptM1eTGuBXKyOJ8Etr8KmPMHiCYGEHYtLUXehGBt00VRhtUgpf+GCrYBKg/C7dUfy5TgNwcXkniI0p0WT9Hhb+KJKgqWOCFbDunsUcGkrzc8C1ozF9QiPBUTiUszO/KnGAv8rDDWqNRpkhMZimNhIcX7ROSXPmKUkJfpgUebFVe+AlsjPjlaYGnlfv0PMi6t+9xeA4y0hD+iPWkDjSc6ihCz+AOPAK9Wtw4A6XTmrb4DB0T9Mva7HKGSRy93JFksefVXUcotvotFn2nwS6p/YmFLFsOsovAgMBAAECggEARb9okqaCzIiEHTGZ7JXvUGYbMLhFhWzU+PbvYHPQhD1677ILjxSIxtt/jkFdBgANWbp8i/StdRZ41Og3suSna7UBlfpfgx1VqA1Ss4zGT6EyMYdXt1/P75mUrVt6zqirrP8O9tb+3wZK02VXLL58xH4I5GIvMCKVG+XyIpoBKUGTGUKiYeAdSHzCDhU/efEmJ3/nBZ7yRYPUYSlF56w9lMzHc9CcqIk6hUImcc7dsIT8aJCyOvQioZptA15LhP36l3z21oZ6/1Z1xRUicHfJQJi0hhRVOjQaNGbgACUnVRVulcPDgKrBRlVt3w5dK5m80jAIyXhnsD7Kj1aLMGeFKQKBgQDuyHy3o915nyjFapmKVpW1qtZO1d84xyoPWS8Sk4bt4nglDpR2x/7BwPM0AB+aT+1zuuExI+/OYI8hBCh7QtqOVaDEl4Qrh6HZDqcUK2BBflvKXYBk7d+UKpuZZn/PwsWcjF/Es7/7CPFqhdBtNd8vruLF49pyit5t7u9Nak48WwKBgQC2z9hbCuG/qHtGAsUk/rm7i0cPGZPUWFjIPeD8ezR1hYlQ0e+d3Tx/xGQK3v9AjOYeIY6AxJR5AABd/2bC6ImLl1rs8NJz0e89+xYHPLi7JrbcHT/eY/Iky4T4eIA2Dg0eStoIFfHqYJQRhyYCPR+h/T77A8XeSEmMW9hAmPmhvQKBgQCagmKpVcBPHZz9OYBG0sYm+neYJa4+iCmAKv5Zr9qEfaGuoOOShNElQJxejqHkcUm+NDPZX16iFTsoaw9iyxyvM1tHOp/MpwQkduXIGFU9q+zrYltdc8rTjkqHFZsorei+5tplZsaYQu4sNpBqyowzx59323uT2KYbTpvMZThgtwKBgD2k2mzgv3zUQDU8a+PsrQ6LiXuTAWFCJTXof7xDg035qHMDR4xw9JyUybNMvL+0g0g3woizQOmIUZdgrvMcXH0gnX12O1Dowoag6y2nkRcyl8ijaE0CYL19jyoF4B3aIRxM2zaMx9VjmapLa0qn98m0zo7wF8G7mGlm8wXdT5f1AoGBAKIPRS+DXwsTsJK5LjMguTCrax0hWc9dov0UGQDb2+wUQYdRXx7UytxJYYQScrsLc0rvYWp71f17wg2QRlZsF/oZhyWL27jZ22lxz/RYq4loBQT5if0S3qsdsTWkLRfi1/bsmyCxfqcM+3FdgS8fOQ95YxYL7W8vT2fTFVBUTPHO
      alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgZAJkOGavIsM/mCIwxaFYlqsMsETUXMUz54u/+MZyRoMb/Bp2EuQTsjaMqQvnMjt7wmz2khuXvrWrxU5We9qqEYXn1xYLPujLwXdxyrFIK1scaY+fWRqBhI9cjQRNsB4YuSJhr8PAJ3OVQJpsIPu09aoannuUGIDnAMvJCBm45HOvnNHGwuf+zsKLh4OqbawngLJu6HhVnN0hdsXilcJmumu5u92J/H4tE9WHbOMto2FIM3f/xQglt2vQvq3g3PQv6FkdQmVfmfLdCdSz0SewQ/BHmB3uXVVCtMU2j627CdiThZeUKp9mCOku2W0JnqLy6SwFOi2FrWn4fJzI5m4SwIDAQAB
      notify_url: http://jp-tyo-ntt-1.natfrp.cloud:30525/api/payment/notify/success
      return_url: http://payment.gmall.com/pay/success.html
      sign_type: RSA2
      charset: utf-8
      gatewayUrl: https://openapi.alipaydev.com/gateway.do




