server:
  port: 10001

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  elasticsearch:
    rest:
      uris: http://192.168.10.129:9200
      connection-timeout: 1s
      read-timeout: 30s

logging:
  level:
    tracer: trace
    com.atguigu.gmall.search: trace