server:
  port: 7001

spring:
  datasource:
    url: jdbc:mysql://192.168.10.129:3306/gmall_product?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    #active: sharding #application.yaml 永远生效 + active激活的文件
    include: sharding
#  zipkin:
#    base-url: http://192.168.10.129:9411/
#    sender:
#      type: web
#  #配置采样率
#  sleuth:
#    sampler:
#      rate: 100

app:
  minio:
    endpoint: http://192.168.10.129:9000
    access-key: admin
    secret-key: admin123456
    bucket-name: mall-oss

